#!/usr/bin/env php
<?php

use Symfony\Component\Console\Input\ArgvInput;

define('LARAVEL_START', microtime(true));

if (file_exists($maintenance = __DIR__.'/storage/framework/maintenance.php')) {
    require $maintenance;
}

require __DIR__.'/bootstrap/ensure-runtime-dirs.php';

$autoload = __DIR__.'/vendor/autoload.php';
if (! is_file($autoload)) {
    fwrite(STDERR, "Error: no existe vendor/autoload.php.\n");
    fwrite(STDERR, "Tras git clone ejecute primero: composer install\n");
    fwrite(STDERR, "Luego: npm install && npm run instances:bootstrap\n");
    exit(1);
}

require $autoload;

$app = require_once __DIR__.'/bootstrap/app.php';

$status = $app->handleCommand(new ArgvInput);

exit($status);
