sonar.projectKey=omnichannel-sass
sonar.projectName=Omnichannel SaaS Platform
sonar.projectVersion=1.0

sonar.sources=app,config,routes,database
sonar.tests=tests
sonar.sourceEncoding=UTF-8

sonar.exclusions=vendor/**,storage/**,bootstrap/cache/**,node_modules/**,public/build/**,resources/views/**
sonar.test.inclusions=tests/**/*

# Generar con: vendor/bin/phpunit --coverage-clover build/coverage/clover.xml
sonar.php.coverage.reportPaths=build/coverage/clover.xml
