/** @type {import('tailwindcss').Config} */
export default {
    content: [
        './vendor/laravel/framework/src/Illuminate/Pagination/resources/views/*.blade.php',
        './storage/framework/views/*.php',
        './resources/views/**/*.blade.php',
        './resources/js/**/*.vue',
    ],
    darkMode: 'class',
    theme: {
        extend: {
            colors: {
                'primary': '#000000',
                'secondary': '#515f74',
                'surface': '#fcf8fa',
                'surface-container-low': '#f6f3f5',
                'surface-container': '#f0edef',
                'surface-container-high': '#eae7e9',
                'surface-container-highest': '#e4e2e4',
                'surface-container-lowest': '#ffffff',
                'surface-bright': '#fcf8fa',
                'surface-dim': '#dcd9db',
                'surface-variant': '#e4e2e4',
                'on-surface': '#1b1b1d',
                'on-surface-variant': '#45464d',
                'outline': '#76777d',
                'outline-variant': '#c6c6cd',
                'secondary-fixed': '#d5e3fd',
                'secondary-fixed-dim': '#b9c7e0',
                'on-secondary-fixed': '#0d1c2f',
                'on-secondary-fixed-variant': '#3a485c',
                'primary-container': '#131b2e',
                'on-primary-container': '#7c839b',
                'primary-fixed': '#dae2fd',
                'primary-fixed-dim': '#bec6e0',
                'on-primary-fixed': '#131b2e',
                'on-primary': '#ffffff',
                'secondary-container': '#d5e3fd',
                'on-secondary-container': '#57657b',
                'on-secondary': '#ffffff',
                'error': '#ba1a1a',
                'error-container': '#ffdad6',
                'on-error-container': '#93000a',
                'on-error': '#ffffff',
                'inverse-surface': '#303032',
                'inverse-on-surface': '#f3f0f2',
                'inverse-primary': '#bec6e0',
                'tertiary': '#000000',
                'tertiary-container': '#191c1e',
                'on-tertiary': '#ffffff',
                'on-tertiary-container': '#818486',
                'tertiary-fixed': '#e0e3e5',
                'tertiary-fixed-dim': '#c4c7c9',
                'on-tertiary-fixed': '#191c1e',
                'on-tertiary-fixed-variant': '#444749',
                'surface-tint': '#565e74',
            },
            fontFamily: {
                'inter': ['Inter', 'sans-serif'],
            },
            spacing: {
                'xs': '4px',
                'sm': '8px',
                'md': '16px',
                'lg': '24px',
                'xl': '32px',
                '2xl': '48px',
                'gutter': '20px',
                'margin': '24px',
                'unit': '4px',
            },
            fontSize: {
                'h1': ['32px', { lineHeight: '40px', letterSpacing: '-0.02em', fontWeight: '700' }],
                'h2': ['24px', { lineHeight: '32px', letterSpacing: '-0.01em', fontWeight: '600' }],
                'h3': ['20px', { lineHeight: '28px', fontWeight: '600' }],
                'body-lg': ['16px', { lineHeight: '24px', fontWeight: '400' }],
                'body-md': ['14px', { lineHeight: '20px', fontWeight: '400' }],
                'data-tabular': ['14px', { lineHeight: '20px', fontWeight: '500' }],
                'caption': ['12px', { lineHeight: '16px', fontWeight: '400' }],
                'label-caps': ['12px', { lineHeight: '16px', letterSpacing: '0.05em', fontWeight: '700' }],
            },
            borderRadius: {
                'DEFAULT': '0.125rem',
                'sm': '0.125rem',
                'md': '0.25rem',
                'lg': '0.25rem',
                'xl': '0.5rem',
                'full': '0.75rem',
            },
        },
    },
    plugins: [
        require('@tailwindcss/forms'),
    ],
};
