apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: middleware-ingress
  namespace: platform-middleware
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    nginx.ingress.kubernetes.io/proxy-body-size: "20m"
spec:
  ingressClassName: nginx
  tls:
    - hosts:
        - middleware.example.com
      secretName: middleware-tls
  rules:
    - host: middleware.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: middleware-web
                port:
                  number: 80
