apiVersion: v1
kind: Service
metadata:
  name: middleware-web
  namespace: platform-middleware
spec:
  selector:
    app: middleware-web
  ports:
    - name: http
      port: 80
      targetPort: 8080
  type: ClusterIP
